#!/bin/sh
rm -rf cgi-bin

cd gdbm-1.7.3
make clean
rm -f config.status autoconf.h Makefile
cd ..

cd qDecoder-4.3.1
make clean
cd ..

cd md5
make clean
cd ..

cd adm-1.2
make clean
cd ..

cd cwb-5.0
make clean
cd ..

cd arc-1.0
make clean
cd ..

cd md5genkey-1.0
make clean
cd ..
